# Generated by Django 3.2.2 on 2021-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210521_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='contentType',
            field=models.CharField(default='movie', editable=False, max_length=7),
        ),
    ]
