# Generated by Django 3.2.2 on 2021-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_moviedetail_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='contentType',
            field=models.CharField(default='movie', editable=False, max_length=7),
        ),
    ]
